# Generated by Django 6.0.6 on 2026-07-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_farmerbankdetails_wallet_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerbankdetails',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
